language: node_js
node_js:
- node
after_success:
- npm run coverage
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: bruno.krebs@digituz.com.br
  api_key:
    secure: Pk6GunxkWjFlegM9wgDpvr5yxegT5KNlwQQnRDCltoRKqTeWNpXIZ3QvJc9xjknA6PKgEuKCj/7w3DK5y4tM08R9PwFFqeHr9JqSp/yA8SSHfBPtnXSpO61/S/B1eaudAO9GiaMM9O8/mre69DvXxn3hGcDnUPblRLIy6g6i+nkHGEjAY+f6Uc9U3BcnqILCcva9nubloEhH4mtVOWHENvUsAIOmKCqrNBB7/Of77VydEWrVgAts8HI2rg5fcmczKLfJwj7hX1fG+gYi0rRPV0sLyKZX7WW2ai08bfykGJzTWJ9CDgTNdg2Vy1qCVa8yR/ABInSZ4IDBPMILwM/fNfAAAa+iTno8MsBgmseK/oY/uMbCrbH2J6NECsxkdzZXUY0Dg8m/yReSIa6Lm8zsTZw5Zz7ZIypLUA4lJJgDSmyH868C/FtKktIWbUq+tRWzf/Ke1KLPDT9wL3bM0fVLz/5W3Zug7IUbWkjc8/Zl0z7wkN+43enNs/4pnzJAu4xZs7XOROgIXxFzcXwu8LByWA2JBUGxn/CWyBGlr0ao/f+cgsQ8YPduxqzkAZBNHf5gnTfXzfsZaKwERxm9mb1BQm8YlO2aiv/vMeUG0S0FOAVhRr3p0K83td0VS7GCrS1k91CMKKc5UBA1NS98BZ5yGXv3+8EjtvRUfJsJMJe2wrs=
  on:
    tags: true
    repo: auth0-blog/auth0-web
